language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="http://w3c.github.io/selection-api/W3CTRMANIFEST"
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
  - secure: "lKRt+pehDA4qR89jTE+QzUHlfxmwShuNZRkkrHLjNbUc0MpzKJcxW1MWZb65dFEEgDA9hKcu8NV79fbhBF/jWD7XgSiZw0n3lHrNr/8jrufCr8owVDH+LBAqGQJYMnM7GaSwMTgBNWF2+r40Oj7x5BXeNEQmc1YDZaWeixyLuzA="
script:
- echo "ok"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"'
